### ISSUE TITLE
Version 1.05: What are the limitations of the viewer?

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/files_photospheres#25] opened 2019-07-13 15:09 UTC
That one works in Google Photo, but in Nextcloud it is black only:
https://mega.nz/#!MRFTyQSY!I_ArEsqVuW2tIXL3HqP7mwdVEzZ79DAfwI6O2VU5-R0

**Comment by R0Wi** [comment] 2019-07-14 15:42
I'm sorry but i can't reproduce the issue. I downloaded your image and loaded it in various NC instances with the panorama-viewer version 1.0.5 installed and i had no problems with viewing it.

Could you take a look at your dev-console?

**Comment by Sanookmakmak** [comment] 2019-07-14 18:38
Sorry, i tested with Firefox 68.0 64bit only - i got a black page with it.

![beach 360](https://user-images.githubusercontent.com/24833757/61187848-2abf2600-a677-11e9-9333-8a4ca432c152.png)

Chrome, Opera and Edge are working well.

Smaller panoramas are working in Firefox
![edfu sphere](https://user-images.githubusercontent.com/24833757/61187851-30b50700-a677-11e9-9f44-f716c23ac05e.png)

**Comment by R0Wi** [comment] 2019-07-14 18:50
Ok, well that seems to be a browser problem which is directly related to the photosphere.js library. So i'll close this for now.

**Closed by R0Wi** 2019-07-14 18:50 UTC
