### ISSUE TITLE
Not working with 2FA and/or sharing

### ISSUE THREAD

**Issue by jkoopmann** [nextcloud/files_photospheres#8] opened 2019-05-01 18:42 UTC
Hi,

I have 2FA enabled. When I click on a PANO_.jpg the viewer opens but asks for my credentals. If I enter username/password I get "Cannot load image" instead of getting the 2FA question. Why is it asking for access credentials anyways?

If I share a folder and access the folder via the link and click on the PANO_.jpg I only get the Nextcloud viewer.

**Comment by R0Wi** [comment] 2019-05-05 08:54
Hi @jkoopmann ,

which version of nextcloud do you use?

**Comment by jkoopmann** [comment] 2019-05-05 13:03
15.0.7

**Comment by R0Wi** [comment] 2019-05-08 15:50
Thats strange, i actually can't reproduce the mentioned behaviour. I tested it with the "Two-Factor TOTP Provider"-App. Which one do you use?
I logged into my NC instance by username and password, then i provided the second factor (code) by opening the TOTP-App on my android-smartphone. After that i've been successfully logged in and i was able to open an "PANO_..."-image in the viewer without any ask for credentials. Same applied to the sharing option.

So could you provide some more information to us please?

**Comment by cratoo** [comment] 2019-05-14 18:50
@R0Wi did you note "share a folder"? If I share a single picture it works perfectly, if I share a whole folder, the PANO_ images dont show up as photospheres but in the usual gallery app.

**Comment by jkoopmann** [comment] 2019-05-17 09:58
Just switched to NC16 and hence cannot test... Will the plugin be available for NC16?

**Comment by R0Wi** [comment] 2019-05-17 10:27
We're actually working on that. Please refer to https://github.com/nextcloud/files_photospheres/issues/7 for further information.

**Comment by SudoHenk** [comment] 2019-06-28 11:33
I also cannot reproduce the 2FA request dialog. I will close the issue for now, please report back if you encounter this again.

Sharing a folder and then opening the photosphere viewer is not supported as of yet.

**Closed by SudoHenk** 2019-06-28 11:33 UTC

**Comment by R0Wi** [comment] 2019-06-28 11:42
Just a note on this: i couldn't reproduce the issue neither. The folder-share stuff has moved to #17, i am working on this feature.
